language: go
go:
- 1.12.5
stages:
  - build
  - deploy
env:
  - IMAGE=testautomationci/jukebox-server:latest
script:
- CGO_ENABLED=0 GOARCH=386 go build -ldflags=-s -o jukebox_server
- echo $DOCKER_PASS | docker login -u $DOCKER_LOGIN --password-stdin
- docker build -t $IMAGE .
- docker push $IMAGE
