language: go
go:
- 1.12.5
stages:
  - build
  - deploy
env:
  - IMAGE=testautomationci/jukebox-server:latest
script:
- CGO_ENABLED=0 GOARCH=386 go build -ldflags=-s build -o jukebox_server
- docker login -u "$DOCKER_LOGIN" -p "$DOCKER_PASS"--password-stdin
- docker build -t $IMAGE .
- docker push $IMAGE
